# ✅ Region to Public IPs Output
output "vpn_public_ips" {
  value = tomap({
    "us-east-1"      = try(flatten([for m in module.vpn_us_east_1[*] : m.public_ips]), [])
    "us-east-2"      = try(flatten([for m in module.vpn_us_east_2[*] : m.public_ips]), [])
    "us-west-1"      = try(flatten([for m in module.vpn_us_west_1[*] : m.public_ips]), [])
    "us-west-2"      = try(flatten([for m in module.vpn_us_west_2[*] : m.public_ips]), [])
    "ca-central-1"   = try(flatten([for m in module.vpn_ca_central_1[*] : m.public_ips]), [])
    "sa-east-1"      = try(flatten([for m in module.vpn_sa_east_1[*] : m.public_ips]), [])
    "eu-west-1"      = try(flatten([for m in module.vpn_eu_west_1[*] : m.public_ips]), [])
    "eu-west-2"      = try(flatten([for m in module.vpn_eu_west_2[*] : m.public_ips]), [])
    "eu-west-3"      = try(flatten([for m in module.vpn_eu_west_3[*] : m.public_ips]), [])
    "eu-north-1"     = try(flatten([for m in module.vpn_eu_north_1[*] : m.public_ips]), [])
    "eu-central-1"   = try(flatten([for m in module.vpn_eu_central_1[*] : m.public_ips]), [])
    "eu-central-2"   = try(flatten([for m in module.vpn_eu_central_2[*] : m.public_ips]), [])
    "eu-south-1"     = try(flatten([for m in module.vpn_eu_south_1[*] : m.public_ips]), [])
    "eu-south-2"     = try(flatten([for m in module.vpn_eu_south_2[*] : m.public_ips]), [])
    "me-central-1"   = try(flatten([for m in module.vpn_me_central_1[*] : m.public_ips]), [])
    "me-south-1"     = try(flatten([for m in module.vpn_me_south_1[*] : m.public_ips]), [])
    "il-central-1"   = try(flatten([for m in module.vpn_il_central_1[*] : m.public_ips]), [])
    "af-south-1"     = try(flatten([for m in module.vpn_af_south_1[*] : m.public_ips]), [])
    "ap-south-1"     = try(flatten([for m in module.vpn_ap_south_1[*] : m.public_ips]), [])
    "ap-south-2"     = try(flatten([for m in module.vpn_ap_south_2[*] : m.public_ips]), [])
    "ap-southeast-1" = try(flatten([for m in module.vpn_ap_southeast_1[*] : m.public_ips]), [])
    "ap-southeast-2" = try(flatten([for m in module.vpn_ap_southeast_2[*] : m.public_ips]), [])
    "ap-southeast-3" = try(flatten([for m in module.vpn_ap_southeast_3[*] : m.public_ips]), [])
    "ap-southeast-4" = try(flatten([for m in module.vpn_ap_southeast_4[*] : m.public_ips]), [])
    "ap-southeast-5" = try(flatten([for m in module.vpn_ap_southeast_5[*] : m.public_ips]), [])
    "ap-southeast-7" = try(flatten([for m in module.vpn_ap_southeast_7[*] : m.public_ips]), [])
    "ap-east-1"      = try(flatten([for m in module.vpn_ap_east_1[*] : m.public_ips]), [])
    "ap-northeast-1" = try(flatten([for m in module.vpn_ap_northeast_1[*] : m.public_ips]), [])
    "ap-northeast-2" = try(flatten([for m in module.vpn_ap_northeast_2[*] : m.public_ips]), [])
    "ap-northeast-3" = try(flatten([for m in module.vpn_ap_northeast_3[*] : m.public_ips]), [])
  })
}